dist: trusty
language: cpp
compiler: gcc
before_install:
  - sudo add-apt-repository -y ppa:jonathonf/gcc-7.1
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
script: make
